# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: deploy tutorial (only on push to master branch)
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install mkdocs
      run: |
          pip install mkdocs
          mkdocs --version

    - name: build tutorial
      run: mkdocs gh-deploy --force
